# Generated by Django 5.0.6 on 2024-06-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0003_alter_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socket_api.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socket_api.room')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='message_forwarded',
            field=models.ManyToManyField(related_name='forwarded_message', through='socket_api.ForwardedMessage', to='socket_api.room'),
        ),
    ]
