# Generated by Django 5.0.6 on 2024-06-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0005_alter_message_options_message_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_forwarded',
        ),
        migrations.DeleteModel(
            name='ForwardedMessage',
        ),
    ]
