# Generated by Django 5.0.6 on 2024-06-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0006_remove_message_message_forwarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded', to='socket_api.message'),
        ),
    ]
