# Generated by Django 5.0.6 on 2024-06-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0007_message_forwarded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded', to='socket_api.message'),
        ),
    ]
