# Generated by Django 5.0.6 on 2024-06-13 15:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0010_customuser_show_last_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AddField(
            model_name='room',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='members', through='socket_api.GroupMembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
