# Generated by Django 5.0.6 on 2024-06-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0011_alter_customuser_options_room_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterField(
            model_name='message',
            name='forwarded_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded', to='socket_api.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socket_api.message'),
        ),
    ]
