# Generated by Django 5.0.6 on 2024-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_api', '0012_alter_room_options_alter_message_forwarded_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delete_for_me',
            field=models.BooleanField(default=False),
        ),
    ]
